// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "waffle_thrift.h"
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/PlatformThreadFactory.h>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/server/TThreadPoolServer.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportUtils.h>

#include <thrift/server/TThreadedServer.h>
#include <thrift/server/TServer.h>
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/PlatformThreadFactory.h>
#include <thrift/server/TNonblockingServer.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/transport/TNonblockingServerSocket.h>
#include <thrift/transport/TServerSocket.h>

#include <thrift/TToString.h>
#include <thrift/stdcxx.h>

#include <iostream>
#include <stdexcept>
#include <sstream>
#include <thread>

using namespace std;
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace ::apache::thrift::concurrency;

class waffle_thriftHandler : virtual public waffle_thriftIf
{
public:
  waffle_thriftHandler()
  {
    // Your initialization goes here
  }

  int64_t get_client_id()
  {
    // Your implementation goes here
    printf("get_client_id\n");
  }

  void register_client_id(const int32_t block_id, const int64_t client_id)
  {
    // Your implementation goes here
    printf("register_client_id\n");
  }

  void async_get(const sequence_id &seq_id, const std::string &key)
  {
    // Your implementation goes here
    printf("async_get\n");
  }

  void async_put(const sequence_id &seq_id, const std::string &key, const std::string &value)
  {
    // Your implementation goes here
    printf("async_put\n");
  }

  void async_get_batch(const sequence_id &seq_id, const std::vector<std::string> &keys)
  {
    // Your implementation goes here
    printf("async_get_batch\n");
  }

  void async_put_batch(const sequence_id &seq_id, const std::vector<std::string> &keys, const std::vector<std::string> &values)
  {
    // Your implementation goes here
    printf("async_put_batch\n");
  }

  void get(std::string &_return, const std::string &key)
  {
    // Your implementation goes here
    printf("get\n");
  }

  void put(const std::string &key, const std::string &value)
  {
    // Your implementation goes here
    printf("put\n");
  }

  void get_batch(std::vector<std::string> &_return, const std::vector<std::string> &keys)
  {
    // Your implementation goes here
    printf("get_batch\n");
  }

  void put_batch(const std::vector<std::string> &keys, const std::vector<std::string> &values)
  {
    // Your implementation goes here
    printf("put_batch\n");
  }
};

class WaffleCloneFactory : virtual public waffle_thriftIfFactory
{
public:
  ~WaffleCloneFactory() override = default;
  waffle_thriftIf *getHandler(const ::apache::thrift::TConnectionInfo &connInfo) override
  {
    std::shared_ptr<TSocket> sock = std::dynamic_pointer_cast<TSocket>(connInfo.transport);
    sock->setSendTimeout(1200000);

    std::cout << "Incoming connection\n";
    std::cout << "\tSocketInfo: " << sock->getSocketInfo() << "\n";
    std::cout << "\tPeerHost: " << sock->getPeerHost() << "\n";
    std::cout << "\tPeerAddress: " << sock->getPeerAddress() << "\n";
    std::cout << "\tPeerPort: " << sock->getPeerPort() << "\n";

    return new waffle_thriftHandler;
  }
  void releaseHandler(waffle_thriftIf *handler) override
  {
    delete handler;
  }
};

int main(int argc, char **argv)
{
  int port = 9090;
  int num_threads = 4;
  /*
  ::apache::thrift::stdcxx::shared_ptr<waffle_thriftHandler> handler(new waffle_thriftHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessorFactory> processor(stdcxx::make_shared<WaffleCloneFactory>(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  std::shared_ptr<ThreadManager> threadManager = ThreadManager::newSimpleThreadManager(15);
  std::shared_ptr<PosixThreadFactory> threadFactory = std::shared_ptr<PosixThreadFactory>(new PosixThreadFactory());
  threadManager->threadFactory(threadFactory);
  threadManager->start();

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  */

  auto clone_factory = std::make_shared<WaffleCloneFactory>();
  auto proc_factory = std::make_shared<waffle_thriftProcessorFactory>(clone_factory);
  auto socket = std::make_shared<TNonblockingServerSocket>(port);
  socket->setSendTimeout(1200000);

  std::shared_ptr<ThreadManager> threadManager = ThreadManager::newSimpleThreadManager(15);
  std::shared_ptr<PosixThreadFactory> threadFactory = std::shared_ptr<PosixThreadFactory>(new PosixThreadFactory());
  threadManager->threadFactory(threadFactory);
  threadManager->start();
  auto server = std::make_shared<TNonblockingServer>(proc_factory, std::make_shared<TBinaryProtocolFactory>(), socket, threadManager);

  server->setNumIOThreads(num_threads);

  server->serve();


  std::thread proxy_serve_thread([&server] { server->serve(); });
  std::cout << "Proxy server is reachable" << std::endl;
  return 0;
}
