// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "waffle_thrift.h"
#include "nln_proxy.h"
#include "nln_client.h"
#include "nln_levels.h"

#include "waffle/util.h"
#include "waffle/thrift_response_client_map.h"

#include <thrift/concurrency/ThreadManager.h>
#include <thrift/concurrency/PlatformThreadFactory.h>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/server/TThreadPoolServer.h>
#include <thrift/server/TThreadedServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportUtils.h>
#include <thrift/server/TServer.h>
#include <thrift/concurrency/ThreadManager.h>
#include <thrift/server/TNonblockingServer.h>
#include <thrift/transport/TNonblockingServerSocket.h>
#include <thrift/TToString.h>
#include <thrift/stdcxx.h>

#include <iostream>
#include <stdexcept>
#include <sstream>
#include <thread>
#include <atomic>
#include <unordered_map>
#include <vector>
#include <unistd.h>
#include <fstream>
#include <algorithm>
#include <future>
#include <random>
#include <unordered_set>
#include <string>
#include <iterator>
#include <algorithm>
#include <sys/stat.h>
#include <iostream>
#include <chrono>
#include <math.h>

using namespace std;
using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;
using namespace ::apache::thrift::concurrency;

class waffle_thriftHandler : virtual public waffle_thriftIf
{
public:
  waffle_thriftHandler(std::atomic<int64_t> &client_id_gen,
                       std::shared_ptr<::apache::thrift::protocol::TProtocol> prot,
                       std::shared_ptr<thrift_response_client_map> &id_to_client, std::shared_ptr<nln_proxy> proxy) : prot_(std::move(prot)),
                                                                                                                      client_(std::make_shared<thrift_response_client>(prot_)),
                                                                                                                      registered_client_id_(-1),
                                                                                                                      client_id_gen_(client_id_gen),
                                                                                                                      id_to_client_(id_to_client)
  {

    proxy_ = proxy;
  }

  int64_t get_client_id()
  {
    auto value = client_id_gen_.fetch_add(1L);
    std::cout << "In thrift_handler, client ID is " << value << std::endl;
    return value;
  }

  void register_client_id(const int32_t block_id, const int64_t client_id)
  {
    std::cout << "Register client ID called by client: ID is " << client_id << std::endl;
    registered_client_id_ = client_id;
    id_to_client_->add_client(client_id, client_);
  }

  void async_get(const sequence_id &seq_id, const std::string &key)
  {
    // Your implementation goes here
    printf("async_get\n");
  }

  void async_put(const sequence_id &seq_id, const std::string &key, const std::string &value)
  {
    // Your implementation goes here
    printf("async_put\n");
  }

  void async_get_batch(const sequence_id &seq_id, const std::vector<std::string> &keys)
  {
    // Your implementation goes here
    proxy_->async_get_batch(seq_id, operation_count_++, keys);
    printf("async_get_batch\n");
  }

  void async_put_batch(const sequence_id &seq_id, const std::vector<std::string> &keys, const std::vector<std::string> &values)
  {
    // Your implementation goes here
    std::cout << keys.size() << std::endl;
    std::cout << keys[0] << std::endl;

    // async_put_batch(seq_id, rand_uint32(0, RAND_MAX), keys, values);
    printf("async_put_batch\n");
  }

  void get(std::string &_return, const std::string &key)
  {
    // Your implementation goes here
    printf("get\n");
  }

  void put(const std::string &key, const std::string &value)
  {
    // Your implementation goes here
    printf("put\n");
  }

  void get_batch(std::vector<std::string> &_return, const std::vector<std::string> &keys)
  {
    // Your implementation goes here
    printf("get_batch\n");
  }

  void put_batch(const std::vector<std::string> &keys, const std::vector<std::string> &values)
  {
    // Your implementation goes here
    printf("put_batch\n");
  }

private:
  int operation_count_ = 0;
  std::shared_ptr<::apache::thrift::protocol::TProtocol> prot_;
  std::shared_ptr<nln_proxy> proxy_;
  std::shared_ptr<thrift_response_client> client_;
  int64_t registered_client_id_;
  std::atomic<int64_t> &client_id_gen_;
  std::shared_ptr<thrift_response_client_map> &id_to_client_;
};

class WaffleCloneFactory : virtual public waffle_thriftIfFactory
{
public:
  WaffleCloneFactory(std::shared_ptr<thrift_response_client_map> id_to_client, std::shared_ptr<nln_proxy> proxy)
  {

    id_to_client_ = id_to_client;
    proxy_ = proxy;
  };
  waffle_thriftIf *getHandler(const ::apache::thrift::TConnectionInfo &connInfo) override
  {
    std::shared_ptr<TSocket> sock = std::dynamic_pointer_cast<TSocket>(connInfo.transport);
    sock->setSendTimeout(1200000);

    std::cout << "Incoming connection\n";
    std::cout << "\tSocketInfo: " << sock->getSocketInfo() << "\n";
    std::cout << "\tPeerHost: " << sock->getPeerHost() << "\n";
    std::cout << "\tPeerAddress: " << sock->getPeerAddress() << "\n";
    std::cout << "\tPeerPort: " << sock->getPeerPort() << "\n";

    auto transport = std::make_shared<TFramedTransport>(connInfo.transport);
    std::shared_ptr<TProtocol> protocol(new TBinaryProtocol(transport));

    return new waffle_thriftHandler(client_id_gen_, protocol, id_to_client_, proxy_);
  }
  void releaseHandler(waffle_thriftIf *handler) override
  {
    delete handler;
  }
  ~WaffleCloneFactory() override = default;

private:
  std::shared_ptr<thrift_response_client_map> id_to_client_;
  std::atomic<int64_t> client_id_gen_;
  std::shared_ptr<nln_proxy> proxy_;
};

int main(int argc, char **argv)
{
  int port = 9090;
  int num_threads = 4;

  std::shared_ptr<nln_proxy> proxy_ = std::make_shared<nln_proxy>();
  auto id_to_client = std::make_shared<thrift_response_client_map>();
  void *arguments[3];

  std::cout << "Connecting to level map" << std::endl;
  std::shared_ptr<nln_client> level_map_client = std::make_shared<nln_client>(levels_host, levels_map.port);

  std::vector<std::shared_ptr<nln_client>> levels_clients;

  for (int i = 0; i < levels_len; i++)
  {
    if (levels[i].exists)
    {
      levels_clients.push_back(std::make_shared<nln_client>(levels_host, levels[i].port));
    }
    else
    {
      levels_clients.push_back(std::shared_ptr<nln_client>(nullptr));
    }
  }

  arguments[0] = &id_to_client;
  arguments[1] = &level_map_client;
  arguments[2] = &levels_clients;

  dynamic_cast<nln_proxy &>(*proxy_).init(arguments);

  auto clone_factory = std::make_shared<WaffleCloneFactory>(id_to_client, proxy_);
  auto proc_factory = std::make_shared<waffle_thriftProcessorFactory>(clone_factory);
  auto socket = std::make_shared<TNonblockingServerSocket>(port);
  socket->setSendTimeout(1200000);

  std::shared_ptr<ThreadManager> threadManager = ThreadManager::newSimpleThreadManager(15);
  std::shared_ptr<PosixThreadFactory> threadFactory = std::shared_ptr<PosixThreadFactory>(new PosixThreadFactory());
  threadManager->threadFactory(threadFactory);
  threadManager->start();
  auto server = std::make_shared<TNonblockingServer>(proc_factory, std::make_shared<TBinaryProtocolFactory>(), socket, threadManager);

  server->setNumIOThreads(num_threads);

  server->serve();

  std::thread proxy_serve_thread([&server]
                                 { server->serve(); });
  std::cout << "Proxy server is reachable" << std::endl;
  return 0;
}
